baseURL = 'https://thunderseethe.dev/'
languageCode = 'en-us'
title = "thunderseethe's devlog"
theme = "hugo-coder"
enableEmoji = true
 
[markup.highlight]
tabWidth = 2
style = "github-dark"

[markup.tableOfContents]
startLevel = 1

[params]
author = "thunderseethe"
colorScheme = "auto"
hideColorSchemeToggle = false
info = """
Welcome to my blog.

I write about all things programming languages. My goal is to regurgitate academic papers into a more digestible (but less detailed) format.

I'm currently working on [designing a programming language](series/making-a-language)
"""

[params.goatCounter]
code = "thunderseethe"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/thunderseethe/"

[taxonomies]
tag = "tags"
seriers = "series"


[[menu.main]]
  name = "Posts"
  weight = 1
  url  = "posts/"

[[menu.main]]
  name = "Series"
  weight = 2
  url = "series"

