baseURL = 'https://thunderseethe.dev/'
languageCode = 'en-us'
title = "Thunderseethe's Devlog"
theme = "hugo-coder"
enableEmoji = true
enalbeGitInfo = true
 
[markup.highlight]
tabWidth = 2
style = "github-dark"

[markup.tableOfContents]
startLevel = 1

[params]
author = "THUNDERSEETHE'S DEVLOG"
colorScheme = "auto"
hideColorSchemeToggle = false
info = """
Welcome to my blog.

I write about all things programming languages. My goal is to regurgitate academic papers into a more digestible (but less detailed) format.

I'm currently working on [making a language](series/making-a-language)
"""
customJS =["js/main.js"]

[params.goatCounter]
code = "thunderseethe"

[[params.social]]
name = "Github"
icon = "fa-brands fa-2x fa-github"
weight = 1
url = "https://github.com/thunderseethe/"

[[params.social]]
name = "Bluesky"
icon = "fa-brands fa-2x fa-bluesky"
weight = 2
url = "https://bsky.app/profile/thunderseethe.dev"

[[params.social]]
name = "Email"
icon = "fa fa-2x fa-envelope"
weight = 3
url = "mailto:blog@thunderseethe.dev"


[taxonomies]
tag = "tags"
seriers = "series"


[[menu.main]]
  name = "Posts"
  weight = 1
  url  = "posts/"

[[menu.main]]
  name = "Series"
  weight = 2
  url = "series"

